CREATE TABLE comments (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    comments TEXT NOT NULL,
    commentdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
